name 'gkelle-opsview'
author 'Kellen Gattis <Kellen.Gattis@opsview.com>'
description 'Puppet types and providers to manage Opsview objects, such as hosts, servicechecks, servicegroups, etc.'
source 'https://github.com/gkelle/puppet-opsview'
project_page 'https://github.com/gkelle/puppet-opsview'
version '0.6.0'
